controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  gimbal_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ pitch_joint_motor ]
    velocity:
      joint: pitch_joint
      search_velocity: 6.28
      vel_threshold: 1e-2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      joint: trigger_joint
      search_velocity: 3.1415
      vel_threshold: 0.2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  cover_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ cover_joint_motor ]
    velocity:
      joint: cover_joint
      search_velocity: -2
      vel_threshold: 0.05
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: false
    power:
      effort_coeff: 5.0
      vel_coeff: 0.002
      power_offset: -8.41
    twist_angular: 0.5233
    max_odom_vel: 10.0
    timeout: 0.1
    pid_follow: { p: 8.5, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # OmniController
    wheels:
      left_front:
        pose: [ 0.147, 0.147, 2.356 ]
        joint: left_front_wheel_joint
        roller_angle: 0.
        radius: 0.07625
        pid: { p: 0.33, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        pose: [ 0.147, -0.147, 0.785 ]
        joint: right_front_wheel_joint
        roller_angle: 0.
        radius: 0.07625
        pid: { p: 0.3, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      left_back:
        pose: [ -0.147, 0.147, -2.356 ]
        joint: left_back_wheel_joint
        roller_angle: 0.
        radius: 0.07625
        pid: { p: 0.3, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_back:
        pose: [ -0.147, -0.147, -0.785 ]
        joint: right_back_wheel_joint
        roller_angle: 0.
        radius: 0.07625
        pid: { p: 0.37, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 0.32, i: 15.0, d: 0.0, i_clamp_max: 0.40, i_clamp_min: -0.40, antiwindup: true, publish_state: true }
      pid_pos: { p: 0.0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      k_chassis_vel: 0.0
      k_v: 1.0
      accel: 40.0
    pitch:
      joint: "pitch_joint"
      pid: { p: 0.5, i: 20.0, d: 0.0, i_clamp_max: 0.25, i_clamp_min: -0.25, antiwindup: true, publish_state: true }
      pid_pos: { p: 27.0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      k_v: 1.0
      accel: 40.0
    chassis_vel:
      num_data: 30
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 9.8
      enable_gravity_compensation: false
      mass_origin: [ 0.0293,0.0,0.01 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 0.01
      resistance_coff_qd_16: 0.7
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 0.0
      g: 9.81
      delay: 0.04 # 跟随模式下的发弹延迟
      wait_next_armor_delay: 0.08 # 在中心模式下，等待下一块装甲板和下两块装甲板的delay。给一个远高于临界值的转速，调下两块的delay；再给一个较快的中心模式速度，调下一块的
      wait_diagonal_armor_delay: 0.08
      dt: 0.001
      timeout: 0.001
      publish_rate: 50
      max_switch_angle: 50 # 云台的最大切换角、最小切换角
      min_switch_angle: 2
      ban_shoot_duration: 0.03 # 在云台切换时间内的禁止发射的时间，这段时间内一定打不中，所以禁止，在过了这段时间后，发射是有可能打中下一块装甲板的，枪口和下一块相遇运动
      gimbal_switch_duration: 0.1 # 云台切换角所需时间(0.1)开自瞄和pl读值
      ban_shoot_duration2: 0.025
      gimbal_switch_duration2: 0.027
      max_track_target_vel: 12.0 # 最大跟随速度，即跟随模式和中心模式的临界点
      max_chassis_angular_vel: 12.0 # 自身的陀螺速度，最终作用在切换角上，自身陀螺速度越高、切换角越小
      track_rotate_target_delay: 0.03 # 跟随模式下旋转和平移的delay
      track_move_target_delay: 0.04

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction_left:
      left_friction_wheel:
        joint: "left_friction_wheel_joint"
        pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    friction_right:
      right_friction_wheel:
        joint: "right_friction_wheel_joint"
        pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    trigger:
      joint: "trigger_joint"
      pid: { p: 15.0, i: 0.0, d: 1.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 9
    push_qd_threshold: 0.90
    block_effort: 3.0
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.46
    anti_block_threshold: 0.1
    forward_push_threshold: 0.05
    exit_push_threshold: 0.07
    wheel_speed_drop_threshold: 5.0
    wheel_speed_raise_threshold: 1.2
    freq_threshold: 15.0
