camera_back:
  image_width: 1280
  image_height: 1024
  pixel_format: bgr8
  camera_info_url: ''
  camera_name: galaxy_camera
  camera_frame_id: camera_optical_frame
  frame_id: back_camera_optical_frame
  camera_sn: KE0220040170
  frame_rate: 1000
  exposure_auto: false
  exposure_value: 1600
  enable_imu_trigger: false
